name: FHIR IG CI

on:
  push:
    branches: ["main"]
# pull_request:
    #branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ig-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ig-build.yml

  qa:
    needs: build
    uses: ./.github/workflows/ig-qa.yml

  release:
    needs: qa
    uses: ./.github/workflows/ig-release.yml

  deploy-dev:
    needs: qa
    uses: ./.github/workflows/ig-deploy-dev.yml