name: Deploy Dev (GitHub Pages)

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ig-output
          path: output

      - name: Prepare dev site
        run: |
          VERSION="dev-$(date +%Y%m%d-%H%M%S)"

          mkdir -p .publish/$VERSION
          rsync -a output/ .publish/$VERSION/

          ln -sfn $VERSION .publish/dev

      - name: Create index
        run: |
          cat > .publish/index.html <<EOF
          <h1>FHIR IG Dev</h1>
          <p>Latest: <a href="./dev/">Open Dev</a></p>
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .publish
          keep_files: true